export const SET_MAIN_HUE = "SET_MAIN_HUE";
export const SET_MAIN_SATURATION = "SET_MAIN_SATURATION";
export const SET_MAIN_LIGHTNESS = "SET_MAIN_LIGHTNESS";
export const SET_SECONDARY_HUE = "SET_SECONDARY_HUE";
export const SET_SECONDARY_SATURATION = "SET_SECONDARY_SATURATION";
export const SET_SECONDARY_LIGHTNESS = "SET_SECONDARY_LIGHTNESS";

